project:
  type: website
  output-dir: _site

website:
  title: "Interpretable Text Classification at INSEE"
  navbar:
    logo: assets/light_insee_logo.png
    left:
      - href: index.qmd
        text: "Intro & Setup"
      - href: amazon.qmd
        text: "Amazon"
      - href: clinc150.qmd
        text: "CLINC150"
      - href: naf.qmd
        text: "NAF"
      - href: concepts.qmd
        text: "Concepts"

format:
  html:
    toc: true
    toc-depth: 4
    number-sections: true
    theme: cosmo
    embed-resources: false
    css: styles.css

lang: en

execute:
  python: .venv/bin/python
  echo: false

keep-ipynb: false
